import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const lnter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lnter.className}>
        <Navbar />
        <div className="flex flex-col px-20 py-16">{children}</div>
      </body>
    </html>
  );
}
